name: build-preview-environment

on:
  pull_request:
    types: [assigned, opened, reopened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true

      - name: Install
        # adding --legacy-peer-deps for now until issue in storybook is fixed
        # @see https://github.com/storybookjs/storybook/issues/14119 for reference
        run: |
          npm install --legacy-peer-deps
      
      - name: Build Storybook
        run: |
          npm run build-storybook

      # Private pipeline will deploy to preview environment 
      # If pr is from local branch, it will deploy and add comment to PR.
      # If pr is from forked repository, it will deploy when PR has a preview-environment label
      - name: Archive artiacts
        uses: actions/upload-artifact@v3
        with:
          name: storybook-static
          path: storybook-static

