name: Storybook Build and Deploy
on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths: ['src/**/*']
jobs:
    storybook-build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  check-latest: true
            - name: Install
              # adding --legacy-peer-deps for now until issue in storybook is fixed
              # @see https://github.com/storybookjs/storybook/issues/14119 for reference
              run: |
                  npm install --legacy-peer-deps
            - name: Build Storybook
              run: |
                  npm run build-storybook
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@3.6.2
              with:
                  GITHUB_TOKEN: ${{ secrets.STORYBOOK_ACTION_GITHUB_TOKEN }}
                  BRANCH: master
                  FOLDER: storybook-static
                  CLEAN: true
                  TARGET_FOLDER: docs
